# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe22b39511ff0d8eeda695b08148fb314bf05c7f6fa78b1f71708b56d1d5385059d75d959bf67c7c1a95ce945ff04212752185031b0bd3fdcc1c74aff06d392

test:
  secret_key_base: a5b930aad07e54a537f4918bfee0f941937af4056452dffc8834ff772b0caec7679105bc1e4baf4a63b511c100998e89e7298a73b6109cd5daf83285e6d4afe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
